export NTU_TOOL_DIR=INSTALLDIR
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NTU_TOOL_DIR}/lib
if [ -n "${SCRAM_ARCH}" ]; then
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NTU_TOOL_DIR}/lib/${SCRAM_ARCH}
fi
